### ISSUE TITLE
Template Spec (or Documentation) is Unclear...

### ISSUE THREAD

**Issue by Xalior** [ripplejs/ripple#36]
It seems that templates only work if they are composed of a single DOM element, even if it's a simple <div> ... </div>

This is not obvious in the documentation -- and templates without this minor wrapper element seem not to parse correctly beyond the first element.

It may be this is by design, but, if so - it's not obvious without inspecting all the examples, etc. :)

(no examples provided, but take _any_ of the standard examples, and remove the outer wrapper element... :-1: )

-Dx

**Comment by wryk** [comment]
Yep, like others libraries, ripple only use the first root element.
But you are right, this should be documented somewhere because it's an unexpected behaviour for some developers.

I didn't see documention for this in AngularJS but it trigger an error for this case : https://docs.angularjs.org/error/$compile/tplrt

**Comment by Xalior** [comment]
Angular, Yuk! ;-)

I picked ripple because I like an empty DOM not to need over a 1Meg of supporting (SemiPointlessReduandantFactoryProvider) cruft :)

I have updated https://github.com/ripplejs/ripple/wiki/Composing-Views to make this more clear.

Thanks for the clarification!

-Dx

**Comment by wryk** [comment]
I agree with you, I pick AngularJS as example because it's known.
Thanks for the documentation update !
